# Generated by Django 5.2.10 on 2026-01-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_email_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
