# Generated by Django 5.2.10 on 2026-01-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='products/')),
                ('treat_type', models.CharField(choices=[('cake', 'Cake'), ('cookie', 'Cookie')], max_length=10)),
                ('flavor', models.CharField(choices=[('chocolate', 'Chocolate'), ('strawberry', 'Strawberry'), ('vanilla', 'Vanilla'), ('mango', 'Mango'), ('red_velvet', 'Red Velvet')], max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rating', models.FloatField(default=0)),
                ('options', models.JSONField(default=list)),
                ('popularity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
