# Generated by Django 5.2.10 on 2026-01-28 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_cake', '0003_remove_cakeorder_is_added_to_cart'),
        ('shop', '0003_remove_product_image_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='custom_cake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_cake.cakeorder'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
