# Generated by Django 5.2.10 on 2026-01-30 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_shopcakeorder_cartitem_shop_cake_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='shop_cake_order',
        ),
        migrations.DeleteModel(
            name='ShopCakeOrder',
        ),
    ]
