# Generated by Django 5.2.10 on 2026-01-27 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CakeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(choices=[('chocolate', 'Chocolate'), ('vanilla', 'Vanilla'), ('strawberry', 'Strawberry'), ('butterscotch', 'Butterscotch')], max_length=50)),
                ('weight', models.CharField(max_length=5)),
                ('shape', models.CharField(choices=[('round', 'Round'), ('square', 'Square'), ('heart', 'Heart')], max_length=20)),
                ('color', models.CharField(choices=[('pink', 'Pink'), ('mint', 'Mint'), ('lavender', 'Lavender'), ('buttercream', 'Buttercream')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='cake_refs/')),
                ('delivery_date', models.DateField()),
                ('delivery_time', models.TimeField()),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('is_added_to_cart', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
