# Generated by Django 5.2.10 on 2026-01-27 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_cake', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cakeorder',
            old_name='reference_image',
            new_name='image',
        ),
    ]
