# Generated by Django 5.2.10 on 2026-01-28 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_cake', '0002_rename_reference_image_cakeorder_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cakeorder',
            name='is_added_to_cart',
        ),
    ]
