# Generated by Django 5.2.10 on 2026-01-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('cake', 'Cake'), ('cookie', 'Cookie'), ('treat', 'Treat')], max_length=20)),
                ('flavour', models.CharField(choices=[('chocolate', 'Chocolate'), ('strawberry', 'Strawberry'), ('vanilla', 'Vanilla'), ('mango', 'Mango'), ('red_velvet', 'Red Velvet')], max_length=30)),
                ('weight', models.FloatField(choices=[(0.1, '0.1 Kg'), (0.5, '0.5 Kg'), (1, '1 Kg'), (1.5, '1.5 Kg'), (2, '2 Kg')])),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_vegan', models.BooleanField(default=False)),
                ('is_gluten_free', models.BooleanField(default=False)),
                ('is_sugar_free', models.BooleanField(default=False)),
                ('is_vegetarian', models.BooleanField(default=True)),
                ('is_non_vegetarian', models.BooleanField(default=False)),
                ('popularity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
