# Generated by Django 5.2.10 on 2026-01-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_image_alter_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_gluten_free',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_non_vegetarian',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_sugar_free',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_vegan',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_vegetarian',
        ),
        migrations.AddField(
            model_name='product',
            name='diet_type',
            field=models.CharField(choices=[('Vegan', 'Vegan'), ('Gluten-Free', 'Gluten-Free'), ('Sugar-Free', 'Sugar-Free'), ('Vegetarian', 'Vegitarian'), ('Non-Vegetarian', 'Non-Vegitarian')], default='', max_length=20),
        ),
    ]
